"""Filter StatsBomb events for set-pieces and persist as a Parquet dataset."""
from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

import pandas as pd


LOGGER = logging.getLogger("set_piece_iq.process_set_pieces")


SET_PIECE_TYPES = {"Corner", "Free Kick"}
EXPECTED_COLUMNS = [
    "event_id",
    "match_id",
    "team_name",
    "opponent_name",
    "event_type",
    "location_x",
    "location_y",
    "player_name",
    "receiver_name",
    "outcome",
    "end_location_x",
    "end_location_y",
    "is_goal",
    "is_shot",
]


def configure_logging(verbose: bool) -> None:
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(level=level, format="%(asctime)s [%(levelname)s] %(message)s")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Process StatsBomb set-piece events")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path(__file__).resolve().parent / "events.json",
        help="Path to the raw events JSON generated by get_statsbomb_data.py",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "backend" / "data" / "set_piece_data.parquet",
        help="Destination Parquet file path.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose logging output.",
    )
    return parser.parse_args()


def load_events(path: Path) -> pd.DataFrame:
    LOGGER.info("Loading events from %s", path)
    with path.open("r", encoding="utf-8") as f:
        raw_events: List[Dict[str, Any]] = json.load(f)
    df = pd.DataFrame(raw_events)
    LOGGER.info("Loaded %d total events", len(df))
    return df


def build_match_team_map(events: pd.DataFrame) -> Dict[int, List[str]]:
    LOGGER.debug("Constructing match -> teams map")
    if "team" not in events.columns:
        return {}

    def extract_team_name(value: Any) -> Optional[str]:
        if isinstance(value, dict):
            return value.get("name")
        return None

    teams_df = events[["match_id", "team"]].copy()
    teams_df["team_name"] = teams_df["team"].apply(extract_team_name)
    grouped = teams_df.groupby("match_id")["team_name"].unique()
    return {match_id: [team for team in teams if team] for match_id, teams in grouped.items()}


def extract_location(coord: Any, index: int) -> Optional[float]:
    if isinstance(coord, Iterable):
        try:
            value = list(coord)[index]
            return float(value) if value is not None else None
        except (IndexError, TypeError, ValueError):
            return None
    return None


def determine_outcome(event: Dict[str, Any]) -> str:
    shot = event.get("shot")
    if isinstance(shot, dict):
        outcome = shot.get("outcome")
        if isinstance(outcome, dict) and outcome.get("name"):
            return outcome["name"]
        return "Shot"

    pass_info = event.get("pass")
    if isinstance(pass_info, dict):
        outcome = pass_info.get("outcome")
        if isinstance(outcome, dict) and outcome.get("name"):
            return outcome["name"]
        return "Completed"

    return "Unknown"


def extract_receiver(event: Dict[str, Any]) -> Optional[str]:
    pass_info = event.get("pass")
    if isinstance(pass_info, dict):
        recipient = pass_info.get("recipient")
        if isinstance(recipient, dict):
            return recipient.get("name")
    return None


def is_goal_event(event: Dict[str, Any]) -> bool:
    shot = event.get("shot")
    if isinstance(shot, dict):
        outcome = shot.get("outcome")
        if isinstance(outcome, dict):
            return outcome.get("name") == "Goal"
    return False


def is_shot_event(event: Dict[str, Any]) -> bool:
    return isinstance(event.get("shot"), dict)


def filter_set_pieces(events: pd.DataFrame) -> pd.DataFrame:
    LOGGER.info("Filtering for set-piece events: %s", ", ".join(SET_PIECE_TYPES))
    events = events.copy()

    def get_type_name(value: Any) -> Optional[str]:
        if isinstance(value, dict):
            return value.get("name")
        return None

    events["event_type"] = events["type"].apply(get_type_name)
    filtered = events[events["event_type"].isin(SET_PIECE_TYPES)].reset_index(drop=True)
    LOGGER.info("Retained %d set-piece events", len(filtered))
    return filtered


def enrich_events(events: pd.DataFrame, match_team_map: Dict[int, List[str]]) -> pd.DataFrame:
    LOGGER.debug("Enriching set-piece events with derived columns")
    enriched = events.copy()

    def extract_field(value: Any, key: str) -> Optional[str]:
        if isinstance(value, dict):
            return value.get(key)
        return None

    enriched["team_name"] = enriched["team"].apply(lambda value: extract_field(value, "name"))
    enriched["player_name"] = enriched["player"].apply(lambda value: extract_field(value, "name"))

    def lookup_opponent(row: pd.Series) -> Optional[str]:
        teams = match_team_map.get(row["match_id"], [])
        for team in teams:
            if team and team != row["team_name"]:
                return team
        return None

    enriched["opponent_name"] = enriched.apply(lookup_opponent, axis=1)
    enriched["location_x"] = enriched["location"].apply(lambda coord: extract_location(coord, 0))
    enriched["location_y"] = enriched["location"].apply(lambda coord: extract_location(coord, 1))
    enriched["end_location_x"] = enriched.apply(
        lambda row: extract_location(row.get("shot", {}).get("end_location"), 0)
        if isinstance(row.get("shot"), dict)
        else extract_location(row.get("pass", {}).get("end_location"), 0),
        axis=1,
    )
    enriched["end_location_y"] = enriched.apply(
        lambda row: extract_location(row.get("shot", {}).get("end_location"), 1)
        if isinstance(row.get("shot"), dict)
        else extract_location(row.get("pass", {}).get("end_location"), 1),
        axis=1,
    )
    enriched["receiver_name"] = enriched.apply(lambda row: extract_receiver(row.to_dict()), axis=1)
    enriched["outcome"] = enriched.apply(lambda row: determine_outcome(row.to_dict()), axis=1)
    enriched["is_goal"] = enriched.apply(lambda row: is_goal_event(row.to_dict()), axis=1)
    enriched["is_shot"] = enriched.apply(lambda row: is_shot_event(row.to_dict()), axis=1)
    enriched["event_id"] = enriched["id"]

    selected = enriched[EXPECTED_COLUMNS].copy()
    selected["player_name"] = selected["player_name"].fillna("Unknown")
    selected["receiver_name"] = selected["receiver_name"].fillna("Unknown")
    selected["outcome"] = selected["outcome"].fillna("Unknown")
    return selected


def save_parquet(df: pd.DataFrame, output_path: Path) -> None:
    LOGGER.info("Writing %d events to %s", len(df), output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(output_path, index=False)


def main() -> None:
    args = parse_args()
    configure_logging(args.verbose)

    if not args.input.exists():
        raise FileNotFoundError(f"Input events file not found at {args.input}")

    raw_events = load_events(args.input)
    match_team_map = build_match_team_map(raw_events)
    set_piece_events = filter_set_pieces(raw_events)
    enriched_events = enrich_events(set_piece_events, match_team_map)
    save_parquet(enriched_events, args.output)
    LOGGER.info("Processing complete")


if __name__ == "__main__":
    main()
